// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromoMash.Persistence;

#nullable disable

namespace PromoMash.Persistence.Migrations
{
    [DbContext(typeof(PromoMashDbContext))]
    [Migration("20220404001604_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("PromoMash.Domain.Core.CountryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = "d9e67236ce74444d80907fa6180bc181",
                            CreatedAt = 1649031363819L,
                            Name = "Country-1",
                            UpdatedAt = 1649031363819L
                        },
                        new
                        {
                            Id = "351d4995d4544d00a813437796fee253",
                            CreatedAt = 1649031363819L,
                            Name = "Country-2",
                            UpdatedAt = 1649031363819L
                        });
                });

            modelBuilder.Entity("PromoMash.Domain.Core.ProvinceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = "0ac9f110a7574b8d8d1dcd2297a8670e",
                            CountryId = "d9e67236ce74444d80907fa6180bc181",
                            CreatedAt = 1649031363819L,
                            Name = "Province-1.1",
                            UpdatedAt = 1649031363819L
                        },
                        new
                        {
                            Id = "0d727eb425994829b72c59c225ac62d1",
                            CountryId = "d9e67236ce74444d80907fa6180bc181",
                            CreatedAt = 1649031363819L,
                            Name = "Province-1.2",
                            UpdatedAt = 1649031363819L
                        },
                        new
                        {
                            Id = "061413e3277240798f943f26dc360292",
                            CountryId = "351d4995d4544d00a813437796fee253",
                            CreatedAt = 1649031363819L,
                            Name = "Province-2.1",
                            UpdatedAt = 1649031363819L
                        },
                        new
                        {
                            Id = "f3012cba81a54aff85d2422a39235f36",
                            CountryId = "351d4995d4544d00a813437796fee253",
                            CreatedAt = 1649031363819L,
                            Name = "Province-2.2",
                            UpdatedAt = 1649031363819L
                        });
                });

            modelBuilder.Entity("PromoMash.Domain.Core.ProvinceEntity", b =>
                {
                    b.HasOne("PromoMash.Domain.Core.CountryEntity", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PromoMash.Domain.Core.CountryEntity", b =>
                {
                    b.Navigation("Provinces");
                });
#pragma warning restore 612, 618
        }
    }
}
